kind = "mobile"
previewPath = "/"
title = "Police Audit"
version = "1.0.0"
id = "artifacts/police-audit-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
localPort = 24384
name = "expo"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/police-audit-mobile run dev"

[services.env]
PORT = "24384"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/police-audit-mobile", "run", "build"]
run = ["pnpm", "--filter", "@workspace/police-audit-mobile", "run", "serve"]
